/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_base_d_datos;

import Animaton_componentes.AnimationClass;
import clases.Usuario;
import clases.connection_mysql;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import JTextField.jTextFiel_BR;
import JPassword.JPasswordRound_BD;

/**
 *
 * @author Asus-PC
 */
public class inicio extends javax.swing.JFrame {

    AnimationClass animacion = new AnimationClass();
    String correo = "Correo";
    String Contraseña = "Contraseña";

    public String getContraseña() {
        return Contraseña;
    }

    public void setContraseña(String Contraseña) {
        this.Contraseña = Contraseña;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    public String getCorreo() {
        return correo;
    }

    int iterador = 0;
    int estado = 0;
    String color_Lnegroo = "#000000";
    String color_Lfantasta = "#818181";
    connection_mysql mysql = new connection_mysql("root", "", "proyecto");
    Usuario u = new Usuario();

    public inicio() {
        initComponents();
        this.setLocationRelativeTo(null);

        this.M_mensaje(jTextFiel_BR1, getCorreo());
        this.JPMostrar_Msj(jPasswordRound_BD1, getContraseña());
        this.iniciarJPasswordField();
        this.setIconImage(new ImageIcon(getClass().getResource("/img/imagen.png")).getImage());
        jTextFiel_BR1.setCaretPosition(0);

        /*jPanel1.setBackground(Color.decode("#212121"));
        jPanel2.setBackground(Color.decode("#030303"));
        jpanel1.setBackground(Color.decode("#030303"));
        jpanel2.setBackground(Color.decode("#212121"));
        jLabel5.setForeground(Color.decode("#FAFBE9"));
        jLabel1.setForeground(Color.decode("#FAFBE9"));
        jLabel3.setIcon(new ImageIcon(getClass().getResource("/img/cabeza_N.png")));*/
    }

    public inicio(int n) {
        initComponents();
        this.setLocationRelativeTo(null);

        this.iniciarJPasswordField();
        this.setIconImage(new ImageIcon(getClass().getResource("/img/imagen.png")).getImage());
        jTextFiel_BR1.setCaretPosition(0);

        if (n == 1) {
            jPanel1.setBackground(Color.decode("#212121"));
            jPanel2.setBackground(Color.decode("#030303"));
            jpanel1.setBackground(Color.decode("#030303"));
            jpanel2.setBackground(Color.decode("#212121"));
            jLabel5.setForeground(Color.decode("#FAFBE9"));
            jLabel1.setForeground(Color.decode("#FAFBE9"));
            jLabel3.setIcon(new ImageIcon(getClass().getResource("/img/cabeza_N.png")));
        }
    }

    //guarda el nombre y numero de la localidad del jpanel usuario
    String localidad;
    int num_localidad;
    int problematica;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpanel1 = new jpanel.Jpanel();
        jpanel2 = new jpanel.Jpanel();
        jSeparator6 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jTextFiel_BR1 = new JTextField.jTextFiel_BR();
        jPasswordRound_BD1 = new JPassword.JPasswordRound_BD();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Base de Datos");
        setMinimumSize(new java.awt.Dimension(1064, 745));
        setPreferredSize(new java.awt.Dimension(1064, 745));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(231, 230, 232));
        jPanel1.setForeground(new java.awt.Color(111, 115, 131));
        jPanel1.setPreferredSize(new java.awt.Dimension(1064, 690));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpanel1.setBackground(new java.awt.Color(250, 251, 233));
        jpanel1.setPreferredSize(new java.awt.Dimension(333, 467));

        jSeparator6.setBackground(new java.awt.Color(111, 115, 131));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextFiel_BR1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFiel_BR1FocusLost(evt);
            }
        });
        jTextFiel_BR1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFiel_BR1MouseClicked(evt);
            }
        });
        jTextFiel_BR1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFiel_BR1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFiel_BR1KeyTyped(evt);
            }
        });

        jPasswordRound_BD1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordRound_BD1FocusLost(evt);
            }
        });
        jPasswordRound_BD1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordRound_BD1MouseClicked(evt);
            }
        });
        jPasswordRound_BD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordRound_BD1ActionPerformed(evt);
            }
        });
        jPasswordRound_BD1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordRound_BD1KeyTyped(evt);
            }
        });

        jSeparator7.setBackground(new java.awt.Color(111, 115, 131));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/candado.png"))); // NOI18N

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icono@.png"))); // NOI18N

        javax.swing.GroupLayout jpanel2Layout = new javax.swing.GroupLayout(jpanel2);
        jpanel2.setLayout(jpanel2Layout);
        jpanel2Layout.setHorizontalGroup(
            jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel2Layout.createSequentialGroup()
                .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel14)
                        .addGap(8, 8, 8)
                        .addComponent(jTextFiel_BR1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13)
                        .addGap(4, 4, 4)
                        .addComponent(jPasswordRound_BD1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel2Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel2Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );
        jpanel2Layout.setVerticalGroup(
            jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jpanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTextFiel_BR1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jpanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPasswordRound_BD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 169, 204));
        jLabel1.setText("Iniciar sesión");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Imagen1.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 169, 204));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cabeza_A.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpanel1Layout = new javax.swing.GroupLayout(jpanel1);
        jpanel1.setLayout(jpanel1Layout);
        jpanel1Layout.setHorizontalGroup(
            jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpanel1Layout.setVerticalGroup(
            jpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jpanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, -440, 333, 467));

        jPanel2.setBackground(new java.awt.Color(250, 251, 233));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 169, 204));
        jLabel5.setText("Encuesta");

        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(111, 115, 131));
        jLabel6.setText("Documento de Identidad");

        jSeparator1.setBackground(new java.awt.Color(0, 169, 204));
        jSeparator1.setForeground(new java.awt.Color(0, 169, 204));

        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(111, 115, 131));
        jLabel7.setText("Nombre");

        jSeparator2.setBackground(new java.awt.Color(0, 169, 204));
        jSeparator2.setForeground(new java.awt.Color(0, 169, 204));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(111, 115, 131));
        jLabel8.setText("Correo");

        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField3FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(0, 169, 204));
        jSeparator3.setForeground(new java.awt.Color(0, 169, 204));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(111, 115, 131));
        jLabel10.setText("Telefono");

        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField4FocusLost(evt);
            }
        });
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(0, 169, 204));
        jSeparator5.setForeground(new java.awt.Color(0, 169, 204));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Antonio nariño", "Barrios Unidos", "Bosa", "Chapinero", "Ciudad Bolivar", "Engativa", "Fontibon", "Kennedy", "La candelaria", "Los Mártires", "Puente Aranda", "Rafael Uribe Uribe", "San Cristobal", "Santa Fe", "Suba", "Sumapaz", "Teusaquillo", "Tunjuelito", "Usaquen", "Usme" }));
        jComboBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox1MouseClicked(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "salud", "economia", "seguridad" }));
        jComboBox2.setPreferredSize(new java.awt.Dimension(113, 20));
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton2MouseReleased(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(111, 115, 131));
        jLabel11.setText("Localidad");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(111, 115, 131));
        jLabel12.setText("Problematica");

        jTextField5.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField5FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField5FocusLost(evt);
            }
        });
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(111, 115, 131));
        jLabel15.setText("Apellido");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel10))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel11)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTextField1))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel15))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addGap(6, 6, 6)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jLabel10)
                .addGap(10, 10, 10)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 70, 400, 620));

        jSeparator4.setBackground(new java.awt.Color(0, 169, 204));
        jSeparator4.setForeground(new java.awt.Color(0, 169, 204));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/1620854997209.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 590, 620));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1064, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        iterador++;
        if (iterador == 1) {
            animacion.jPanelYabajo(-440, -10, 5, 10, jpanel1);
            System.out.println("jpanel Abajo");
        } else {
            animacion.jPanelYArriba(-10, -440, 5, 10, jpanel1);
            System.out.println("jpanel Arriba");
            jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            iterador = 0;
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        animacion.jPanelYArriba(-10, -440, 5, 10, jpanel1);
        iterador = 0;
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPasswordRound_BD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordRound_BD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordRound_BD1ActionPerformed

    private void jTextFiel_BR1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFiel_BR1FocusLost
        this.JTBorrar_Msj(jTextFiel_BR1, getCorreo());
    }//GEN-LAST:event_jTextFiel_BR1FocusLost

    private void jTextFiel_BR1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFiel_BR1MouseClicked
        this.JTBorrar_Msj(jTextFiel_BR1, getCorreo());
    }//GEN-LAST:event_jTextFiel_BR1MouseClicked

    private void jPasswordRound_BD1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordRound_BD1MouseClicked
        this.JPBorrar_Msj(jPasswordRound_BD1, getContraseña());
        //  jPasswordRound_BD1.setEchoChar('•');
    }//GEN-LAST:event_jPasswordRound_BD1MouseClicked

    private void jPasswordRound_BD1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordRound_BD1FocusLost
        this.JPMostrar_Msj(jPasswordRound_BD1, getContraseña());
    }//GEN-LAST:event_jPasswordRound_BD1FocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        mysql.MySQL_connection();
        String ID = jTextFiel_BR1.getText();
        String password = jPasswordRound_BD1.getText();
        String tabla = "usuarios";

        u = mysql.getDt_usuario(tabla, ID, password);

        if ((password.trim().length() != 0) && (ID.trim().length() != 0)) {
            if (u != null) {
                jTextFiel_BR1.setText("");
                jPasswordRound_BD1.setText("");

                consulta pr = new consulta(ID, password);
                this.setVisible(false);
                pr.setVisible(true);

                mysql.cerrar_connection();
            } else {
                JOptionPane.showMessageDialog(null, "usuario no existente");
            }
        } else if (ID.trim().length() == 0) {

            JOptionPane.showMessageDialog(null, "llene los campos vacios");
            jTextFiel_BR1.setBackground(new Color(249, 107, 107));
        } else if (password.trim().length() == 0) {
            JOptionPane.showMessageDialog(null, "llene los campos vacios");
            jPasswordRound_BD1.setBackground(new Color(249, 107, 107));
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        mysql.MySQL_connection("root", "proyecto", "");

        String ID = jTextField1.getText();
        String Nombre = jTextField2.getText();
        String Apellido = jTextField5.getText();
        String Correo = jTextField3.getText();
        String Telefono = jTextField4.getText();

        this.seleccionar_localidad();
        this.seleccionar_problematica();

        if (ID.trim().length() == 0) { //retificando que no allan quedado los jtexfield -> ID
            jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));
            estado = 1;
        }

        if (Nombre.trim().length() == 0) { //retificando que no allan quedado los jtexfield -> ID
            jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));

            estado = 1;
        }

        if (Correo.trim().length() == 0) { //retificando que no allan quedado los jtexfield -> ID
            jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));

            estado = 1;
        }

        if (Telefono.trim().length() == 0) { //retificando que no allan quedado los jtexfield -> ID
            jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));

            estado = 1;
        }

        if (Apellido.trim().length() == 0) { //retificando que no allan quedado los jtexfield -> ID
            jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));

            estado = 1;
        }

        if (estado == 1) {
            JOptionPane.showMessageDialog(null, "No deje campos vacios");
        }

        if (estado == 0) {
            int numero = Integer.parseInt(Telefono);
            String N_usuario = Nombre + " " + Apellido;
            int estatus = mysql.Insert_encuestas("encuestas", N_usuario, Correo, numero, num_localidad, problematica, ID);
            if (estatus == 1) {
                JOptionPane.showMessageDialog(null, "Seguardo el dato con exito");
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jComboBox1.setSelectedIndex(0);
                jComboBox2.setSelectedIndex(0);

            } else {
                JOptionPane.showMessageDialog(null, "El Dato no se Guardo");
            }

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized

        if (this.getExtendedState() == MAXIMIZED_BOTH) {
            //  jLabel9.setBounds(30, 70, 730, 620);
            // jPanel2.setBounds(940, 70, 400, 620);
            //jLabel9.setIcon(new ImageIcon(getClass().getResource("/img/fondo_2.jpg")));

            jPanel1.setBounds(0, 0, 1599, 750);
            jPanel2.setBounds(890, 70, 450, 620);
            jpanel1.setLocation(550, -440);
            jLabel9.setBounds(30, 70, 830, 620);

            jLabel5.setLocation(156, 20);
            jTextField1.setBounds(50, 108, 350, 35);
            jTextField2.setBounds(50, 193, 169, 35);
            jTextField5.setBounds(240, 193, 169, 35);
            jTextField3.setBounds(50, 285, 350, 35);
            jTextField4.setBounds(50, 377, 350, 35);
            jLabel6.setLocation(50, 80);
            jLabel7.setLocation(50, 170);
            jLabel15.setLocation(240, 170);
            jLabel8.setLocation(50, 262);
            jLabel10.setLocation(50, 350);
            jLabel11.setLocation(120, 451);
            jLabel12.setLocation(257, 451);
            jSeparator1.setBounds(38, 154, 373, 10);
            jSeparator2.setBounds(38, 246, 373, 10);
            jSeparator3.setBounds(38, 338, 373, 10);
            jSeparator5.setBounds(38, 430, 373, 10);
            jComboBox2.setLocation(245, 479);
            jComboBox1.setLocation(100, 479);
            jButton2.setLocation(190, 550);

        }

    }//GEN-LAST:event_formComponentResized

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        jButton2.setBackground(Color.decode("#4EAD43"));
    }//GEN-LAST:event_jButton2MousePressed

    private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseReleased
        jButton2.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButton2MouseReleased

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setBackground(Color.decode("#4EAD43"));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 169, 204)));
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 173, 179)));
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        estado = 0;
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 169, 204)));
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost

        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 173, 179)));
    }//GEN-LAST:event_jTextField2FocusLost

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        estado = 0;
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusGained

        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 169, 204)));
    }//GEN-LAST:event_jTextField3FocusGained

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost

        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 173, 179)));
    }//GEN-LAST:event_jTextField3FocusLost

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        estado = 0;
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 169, 204)));
    }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusLost

        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 173, 179)));
    }//GEN-LAST:event_jTextField4FocusLost

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        estado = 0;
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jComboBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox1MouseClicked
        estado = 0;
    }//GEN-LAST:event_jComboBox1MouseClicked

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
        estado = 0;
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void jTextField5FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusGained
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 169, 204)));
    }//GEN-LAST:event_jTextField5FocusGained

    private void jTextField5FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField5FocusLost
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 173, 179)));
    }//GEN-LAST:event_jTextField5FocusLost

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        estado = 0;
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jTextFiel_BR1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFiel_BR1KeyPressed
        jTextFiel_BR1.setFocusTraversalKeys(KeyboardFocusManager.FORWARD_TRAVERSAL_KEYS,
                java.util.Collections.EMPTY_SET);
        if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            jPasswordRound_BD1.requestFocus();
            jPasswordRound_BD1.setCaretPosition(0);
        }
    }//GEN-LAST:event_jTextFiel_BR1KeyPressed

    private void jTextFiel_BR1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFiel_BR1KeyTyped
        this.JTBorrar_Msj(jTextFiel_BR1, getCorreo());
    }//GEN-LAST:event_jTextFiel_BR1KeyTyped

    private void jPasswordRound_BD1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordRound_BD1KeyTyped
        this.JPBorrar_Msj(jPasswordRound_BD1, getContraseña());
    }//GEN-LAST:event_jPasswordRound_BD1KeyTyped

    public void M_mensaje(jTextFiel_BR jl, String text) {
        if (jl.getText().length() == 0) {

            jl.setForeground(Color.decode(color_Lfantasta));
            jl.setText(text);
        }
    }

    public void JTBorrar_Msj(jTextFiel_BR fl, String Mensaje) {
        if (fl.getText().equals(Mensaje)) {
            fl.setText("");
            fl.setForeground(Color.decode(color_Lnegroo));
            fl.setCaretPosition(0);
        }
    }

    public void JPBorrar_Msj(JPasswordRound_BD fl, String Mensaje) {
        if (fl.getText().equals(Mensaje)) {
            fl.setText("");
            fl.setForeground(Color.decode(color_Lnegroo));
            fl.setCaretPosition(0);
            fl.setEchoChar('•');

        }
    }

    public void JPMostrar_Msj(JPasswordRound_BD fl, String mensaje) {

        if (fl.getText().length() == 0) {
            fl.setForeground(Color.decode(color_Lfantasta));
            fl.setText(mensaje);
            fl.setEchoChar((char) 0);
        }
    }

    public void iniciarJPasswordField() {

        String mensajePass = jPasswordRound_BD1.getText();
        if (mensajePass.equals(null) || mensajePass.equals("")) {//SOLO SE INICIA EL PLACEHOLDER SI NO EXISTE TEXTO EN EL PASSWORDFIELD

            this.JPMostrar_Msj(jPasswordRound_BD1, getContraseña());
            jPasswordRound_BD1.setEchoChar((char) 0); //SE CONVIERTE A LETRAS LO QUE ENVIAMOS AL JPASSWORDFIELD

        }

    }

    private void seleccionar_localidad() {

        switch (jComboBox1.getSelectedIndex()) {

            case 0 -> {
                estado = 1;
            }
            case 1 -> {
                num_localidad = 15;
                localidad = "Antonio nariño";
            }
            case 2 -> {
                num_localidad = 12;
                localidad = "Barrios unidos";
            }
            case 3 -> {
                num_localidad = 7;
                localidad = "Bosa";
            }
            case 4 -> {
                num_localidad = 2;
                localidad = "Chapinero";
            }
            case 5 -> {
                num_localidad = 19;
                localidad = "Ciudad Bolívar";
            }
            case 6 -> {
                num_localidad = 10;
                localidad = "Engativa";
            }
            case 7 -> {
                num_localidad = 9;
                localidad = "Fontibón";
            }
            case 8 -> {
                num_localidad = 8;
                localidad = "Kennedy";
            }
            case 9 -> {
                num_localidad = 17;
                localidad = "La Candelaria";
            }
            case 10 -> {
                num_localidad = 14;
                localidad = "Los Mártires";
            }
            case 11 -> {
                num_localidad = 16;
                localidad = "Puente aranda";
            }
            case 12 -> {
                num_localidad = 18;
                localidad = "Rafael Uribe Uribe";
            }
            case 13 -> {
                num_localidad = 4;
                localidad = "San Cristobal";
            }
            case 14 -> {
                num_localidad = 3;
                localidad = "Santa Fe";
            }
            case 15 -> {
                num_localidad = 11;
                localidad = "Suba";
            }
            case 16 -> {
                num_localidad = 20;
                localidad = "Sumapaz";
            }
            case 17 -> {
                num_localidad = 17;
                localidad = "La Candelaria";
            }
            case 18 -> {
                num_localidad = 13;
                localidad = "Teusaquillo";
            }
            case 19 -> {
                num_localidad = 6;
                localidad = "Tunjuelito";
            }
            case 20 -> {
                num_localidad = 1;
                localidad = "Usaquen";
            }
            case 21 -> {
                num_localidad = 5;
                localidad = "Usme";
            }

        }

    }

    private void seleccionar_problematica() {

        switch (jComboBox2.getSelectedIndex()) {//seleccion año
            case 0 ->
                estado = 1;
            case 1 ->
                problematica = 1;
            case 2 ->
                problematica = 2;
            case 3 ->
                problematica = 3;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private JPassword.JPasswordRound_BD jPasswordRound_BD1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private JTextField.jTextFiel_BR jTextFiel_BR1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private jpanel.Jpanel jpanel1;
    private jpanel.Jpanel jpanel2;
    // End of variables declaration//GEN-END:variables
}
